version: 0.2
phases:
 pre_build:
   on-failure: ABORT
   commands:
     - pwd
     - TEMP_ROLE=$(aws sts assume-role --role-arn $ASSUME_ROLE_ARN --role-session-name my-session --duration-seconds 3600)
     - export TEMP_ROLE
     - export AWS_ACCESS_KEY_ID="$(echo ${TEMP_ROLE} | jq -r '.Credentials.AccessKeyId')"
     - export AWS_SECRET_ACCESS_KEY="$(echo ${TEMP_ROLE} | jq -r '.Credentials.SecretAccessKey')"
     - export AWS_SESSION_TOKEN="$(echo ${TEMP_ROLE} | jq -r '.Credentials.SessionToken')"
     - git config --global credential.helper '!aws codecommit credential-helper $@'
     - git config --global credential.UseHttpPath true
     - git clone -b master https://git-codecommit.ap-south-1.amazonaws.com/v1/repos/project_name-UI > /dev/null 2>&1
     - cd project_name-UI
     - git fetch --tags
     - latest_tag=$(git describe --tags | tail -n +1)
     - tag_commitid=$(echo $latest_tag | sed 's/\([^-]*\)-\([^-]*\)-g\([^-]*\)/\1-\3/')
     - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin account_id.dkr.ecr.ap-south-1.amazonaws.com
     - docker build -t project_name-ui .
     - docker tag project_name-ui:latest account_id.dkr.ecr.ap-southeast-2.amazonaws.com/project_name-ui:$tag_commitid
     - docker logout account_id.dkr.ecr.ap-south-1.amazonaws.com
     - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin account_id.dkr.ecr.ap-southeast-2.amazonaws.com
     - docker push account_id.dkr.ecr.ap-southeast-2.amazonaws.com/project_name-ui:$tag_commitid